const express = require("express")
const dotenv = require("dotenv")
const { sequelize } = require("./model")
const setupSwagger = require("./swagger/swagger")
const cors = require("cors")
dotenv.config()

//properties
const cartRoute = require("./routes/cartRoute")
const cartItemRoute = require("./routes/cartItemRoute")
const ticketRoute = require("./routes/ticketRoute")
const eventRoute = require("./routes/eventRoute")
const ticketStatusRoute = require("./routes/ticketStatusRoute")
const seatRoute = require("./routes/seatRoute")
const seatTypeRoute = require("./routes/seatTypeRoute")
const bookingRoute = require("./routes/bookingRoute")
const paymentRoute = require("./routes/paymentRoute")
const deliveryRoute = require("./routes/deliveryRoute")
const eventTypeRoute = require("./routes/eventTypeRoute")
const humanCategoryRoute = require("./routes/humanCategoryRoute")
const langRoute = require("./routes/langRoute")
const venuePhoto = require("./routes/venuePhotoRoute")
const venueTypeRoute = require("./routes/venueTypeRoute")
const regionRoute = require("./routes/regionRoute")
const discrictRoute = require("./routes/discrictRoute")
const venueRoute = require("./routes/venueRoute")
const customerRoute = require("./routes/customerRoute")
const customerCardRoute = require("./routes/customerCardRoute")
const customerAddresRoute = require("./routes/customerAddresRoute")
const adminRoute = require("./routes/adminRoute")
const venuevenueTypeRoute = require("./routes/venuevenueTypeRoute")
const countryRoute = require("./routes/countryRoute")
const discountRoute = require("./routes/discountRoute")
const genderRoute = require("./routes/genderRoute")
const sectorRoute = require("./routes/sectorRoute")
const statusRoute = require("./routes/statusRoute")
const app = express()

app.use(express.json())
app.use(
    cors({
        origin: "*"
    })
)

setupSwagger(app)

app.use("/api", cartRoute)
app.use("/api", cartItemRoute)
app.use("/api", ticketRoute)
app.use("/api", ticketStatusRoute)
app.use("/api", eventRoute)
app.use("/api", eventTypeRoute)
app.use("/api", seatRoute)
app.use("/api", seatTypeRoute)
app.use("/api", bookingRoute)
app.use("/api", paymentRoute)
app.use("/api", deliveryRoute)
app.use("/api", langRoute)
app.use("/api", venuePhoto)
app.use("/api", venueTypeRoute)
app.use("/api", humanCategoryRoute)
app.use("/api", regionRoute)
app.use("/api", discrictRoute)
app.use("/api", venueRoute)
app.use("/api", customerRoute)
app.use("/api", customerCardRoute)
app.use("/api", customerAddresRoute)
app.use("/api", adminRoute)
app.use("/api", venuevenueTypeRoute)
app.use("/api", countryRoute)
app.use("/api", discountRoute)
app.use("/api", genderRoute)
app.use("/api", sectorRoute)
app.use("/api", statusRoute)

const PORT = process.env.PORT || 4100

sequelize.sync().then(() => {
    app.listen(PORT, () => {
        console.log(`Server is running on port ${PORT}`);
    })
})